// Copyright 2022 The Im team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'ayah_annotation.dart';
import 'ayah_length.dart';
import 'ayah_translate.dart';
import 'ayah_transliterate.dart';
import 'surah_alphabet.dart';
import 'surah_latin.dart';
import 'surah_translate.dart';
import 'surah_transliterate.dart';

abstract class QuranBinder {
  const QuranBinder();
}

class Quran extends QuranBinder with
  Surah, SurahAlphabet, SurahLatin, SurahTranslate, SurahTransliterate,

  Ayah, AyahLength, AyahTransliterate, AyahTranslate, AyahAnnotation,

  FatihahAlphabet, BaqarahAlphabet, ImranAlphabet, NisaAlphabet, MaidahAlphabet,
  AnamAlphabet, ArafAlphabet, AnfalAlphabet, TaubahAlphabet, YunusAlphabet,
  HudAlphabet, YusufAlphabet, RadAlphabet, IbrahimAlphabet, HijrAlphabet,
  NahlAlphabet, IsraAlphabet, KahfAlphabet, MaryamAlphabet, TahaAlphabet,
  AnbiyaAlphabet, HajjAlphabet, MukminunAlphabet, NurAlphabet, FurqanAlphabet,
  SyuaraAlphabet, NamlAlphabet, QasasAlphabet, AnkabutAlphabet, RumAlphabet,
  LuqmanAlphabet, SajdahAlphabet, AhzabAlphabet, SabaAlphabet, FatirAlphabet,
  YasinAlphabet, SaffatAlphabet, SadAlphabet, ZumarAlphabet, GafirAlphabet,
  FussilatAlphabet, SyuraAlphabet, ZukhrufAlphabet, DukhanAlphabet,
  JasiyahAlphabet, AhqafAlphabet, MuhammadAlphabet, FathAlphabet,
  HujuratAlphabet, QafAlphabet, ZariyatAlphabet, TurAlphabet, NajmAlphabet,
  QamarAlphabet, RahmanAlphabet, WaqiahAlphabet, HadidAlphabet,
  MujadalahAlphabet, HasyrAlphabet, MumtahanahAlphabet, SaffAlphabet,
  JumuahAlphabet, MunafiqunAlphabet, TagabunAlphabet, TalaqAlphabet,
  TahrimAlphabet, MulkAlphabet, QalamAlphabet, HaqqahAlphabet, MaarijAlphabet,
  NuhAlphabet, JinnAlphabet, MuzzamilAlphabet, MuddassirAlphabet,
  QiyamahAlphabet, InsanAlphabet, MursalatAlphabet, NabaAlphabet,
  NaziatAlphabet, AbasaAlphabet, TakwirAlphabet, InfitarAlphabet,
  MutaffifinAlphabet, InsyiqaqAlphabet, BurujAlphabet, TariqAlphabet,
  AklaAlphabet, GasyiyahAlphabet, FajrAlphabet, BaladAlphabet, SyamsAlphabet,
  LailAlphabet, DuhaAlphabet, SyarhAlphabet, TinAlphabet, AlaqAlphabet,
  QadrAlphabet, BayyinahAlphabet, ZalzalahAlphabet, AdiyatAlphabet,
  QariahAlphabet, TakasurAlphabet, AsrAlphabet, HumazahAlphabet, FilAlphabet,
  QuraisyAlphabet, MaunAlphabet, KausarAlphabet, KafirunAlphabet, NasrAlphabet,
  LahabAlphabet, IkhlasAlphabet, FalaqAlphabet, NasAlphabet,

  FatihahLatin, BaqarahLatin, ImranLatin, NisaLatin, MaidahLatin, AnamLatin,
  ArafLatin, AnfalLatin, TaubahLatin, YunusLatin, HudLatin, YusufLatin,
  RadLatin, IbrahimLatin, HijrLatin, NahlLatin, IsraLatin, KahfLatin,
  MaryamLatin, TahaLatin, AnbiyaLatin, HajjLatin, MukminunLatin, NurLatin,
  FurqanLatin, SyuaraLatin, NamlLatin, QasasLatin, AnkabutLatin, RumLatin,
  LuqmanLatin, SajdahLatin, AhzabLatin, SabaLatin, FatirLatin, YasinLatin,
  SaffatLatin, SadLatin, ZumarLatin, GafirLatin, FussilatLatin, SyuraLatin,
  ZukhrufLatin, DukhanLatin, JasiyahLatin, AhqafLatin, MuhammadLatin, FathLatin,
  HujuratLatin, QafLatin, ZariyatLatin, TurLatin, NajmLatin, QamarLatin,
  RahmanLatin, WaqiahLatin, HadidLatin, MujadalahLatin, HasyrLatin,
  MumtahanahLatin, SaffLatin, JumuahLatin, MunafiqunLatin, TagabunLatin,
  TalaqLatin, TahrimLatin, MulkLatin, QalamLatin, HaqqahLatin, MaarijLatin,
  NuhLatin, JinnLatin, MuzzamilLatin, MuddassirLatin, QiyamahLatin, InsanLatin,
  MursalatLatin, NabaLatin, NaziatLatin, AbasaLatin, TakwirLatin, InfitarLatin,
  MutaffifinLatin, InsyiqaqLatin, BurujLatin, TariqLatin, AklaLatin,
  GasyiyahLatin, FajrLatin, BaladLatin, SyamsLatin, LailLatin, DuhaLatin,
  SyarhLatin, TinLatin, AlaqLatin, QadrLatin, BayyinahLatin, ZalzalahLatin,
  AdiyatLatin, QariahLatin, TakasurLatin, AsrLatin, HumazahLatin, FilLatin,
  QuraisyLatin, MaunLatin, KausarLatin, KafirunLatin, NasrLatin, LahabLatin,
  IkhlasLatin, FalaqLatin, NasLatin,

  FatihahTranslate, BaqarahTranslate, ImranTranslate, NisaTranslate,
  MaidahTranslate, AnamTranslate, ArafTranslate, AnfalTranslate, TaubahTranslate,
  YunusTranslate, HudTranslate, YusufTranslate, RadTranslate, IbrahimTranslate,
  HijrTranslate, NahlTranslate, IsraTranslate, KahfTranslate, MaryamTranslate,
  TahaTranslate, AnbiyaTranslate, HajjTranslate, MukminunTranslate, NurTranslate,
  FurqanTranslate, SyuaraTranslate, NamlTranslate, QasasTranslate,
  AnkabutTranslate, RumTranslate, LuqmanTranslate, SajdahTranslate,
  AhzabTranslate, SabaTranslate, FatirTranslate, YasinTranslate, SaffatTranslate,
  SadTranslate, ZumarTranslate, GafirTranslate, FussilatTranslate,
  SyuraTranslate, ZukhrufTranslate, DukhanTranslate, JasiyahTranslate,
  AhqafTranslate, MuhammadTranslate, FathTranslate, HujuratTranslate,
  QafTranslate, ZariyatTranslate, TurTranslate, NajmTranslate, QamarTranslate,
  RahmanTranslate, WaqiahTranslate, HadidTranslate, MujadalahTranslate,
  HasyrTranslate, MumtahanahTranslate, SaffTranslate, JumuahTranslate,
  MunafiqunTranslate, TagabunTranslate, TalaqTranslate, TahrimTranslate,
  MulkTranslate, QalamTranslate, HaqqahTranslate, MaarijTranslate, NuhTranslate,
  JinnTranslate, MuzzamilTranslate, MuddassirTranslate, QiyamahTranslate,
  InsanTranslate, MursalatTranslate, NabaTranslate, NaziatTranslate,
  AbasaTranslate, TakwirTranslate, InfitarTranslate, MutaffifinTranslate,
  InsyiqaqTranslate, BurujTranslate, TariqTranslate, AklaTranslate,
  GasyiyahTranslate, FajrTranslate, BaladTranslate, SyamsTranslate,
  LailTranslate, DuhaTranslate, SyarhTranslate, TinTranslate, AlaqTranslate,
  QadrTranslate, BayyinahTranslate, ZalzalahTranslate, AdiyatTranslate,
  QariahTranslate, TakasurTranslate, AsrTranslate, HumazahTranslate,
  FilTranslate, QuraisyTranslate, MaunTranslate, KausarTranslate,
  KafirunTranslate, NasrTranslate, LahabTranslate, IkhlasTranslate,
  FalaqTranslate, NasTranslate,

  FatihahTransliterate, BaqarahTransliterate, ImranTransliterate,
  NisaTransliterate, MaidahTransliterate, AnamTransliterate, ArafTransliterate,
  AnfalTransliterate, TaubahTransliterate, YunusTransliterate, HudTransliterate,
  YusufTransliterate, RadTransliterate, IbrahimTransliterate, HijrTransliterate,
  NahlTransliterate, IsraTransliterate, KahfTransliterate, MaryamTransliterate,
  TahaTransliterate, AnbiyaTransliterate, HajjTransliterate,
  MukminunTransliterate, NurTransliterate, FurqanTransliterate,
  SyuaraTransliterate, NamlTransliterate, QasasTransliterate,
  AnkabutTransliterate, RumTransliterate, LuqmanTransliterate,
  SajdahTransliterate, AhzabTransliterate, SabaTransliterate, FatirTransliterate,
  YasinTransliterate, SaffatTransliterate, SadTransliterate, ZumarTransliterate,
  GafirTransliterate, FussilatTransliterate, SyuraTransliterate,
  ZukhrufTransliterate, DukhanTransliterate, JasiyahTransliterate,
  AhqafTransliterate, MuhammadTransliterate, FathTransliterate,
  HujuratTransliterate, QafTransliterate, ZariyatTransliterate, TurTransliterate,
  NajmTransliterate, QamarTransliterate, RahmanTransliterate,
  WaqiahTransliterate, HadidTransliterate, MujadalahTransliterate,
  HasyrTransliterate, MumtahanahTransliterate, SaffTransliterate,
  JumuahTransliterate, MunafiqunTransliterate, TagabunTransliterate,
  TalaqTransliterate, TahrimTransliterate, MulkTransliterate, QalamTransliterate,
  HaqqahTransliterate, MaarijTransliterate, NuhTransliterate, JinnTransliterate,
  MuzzamilTransliterate, MuddassirTransliterate, QiyamahTransliterate,
  InsanTransliterate, MursalatTransliterate, NabaTransliterate,
  NaziatTransliterate, AbasaTransliterate, TakwirTransliterate,
  InfitarTransliterate, MutaffifinTransliterate, InsyiqaqTransliterate,
  BurujTransliterate, TariqTransliterate, AklaTransliterate,
  GasyiyahTransliterate, FajrTransliterate, BaladTransliterate,
  SyamsTransliterate, LailTransliterate, DuhaTransliterate, SyarhTransliterate,
  TinTransliterate, AlaqTransliterate, QadrTransliterate, BayyinahTransliterate,
  ZalzalahTransliterate, AdiyatTransliterate, QariahTransliterate,
  TakasurTransliterate, AsrTransliterate, HumazahTransliterate, FilTransliterate,
  QuraisyTransliterate, MaunTransliterate, KausarTransliterate,
  KafirunTransliterate, NasrTransliterate, LahabTransliterate,
  IkhlasTransliterate, FalaqTransliterate, NasTransliterate,

  FatihahLength, BaqarahLength, ImranLength, NisaLength, MaidahLength,
  AnamLength, ArafLength, AnfalLength, TaubahLength, YunusLength, HudLength,
  YusufLength, RadLength, IbrahimLength, HijrLength, NahlLength, IsraLength,
  KahfLength, MaryamLength, TahaLength, AnbiyaLength, HajjLength,
  MukminunLength, NurLength, FurqanLength, SyuaraLength, NamlLength,
  QasasLength, AnkabutLength, RumLength, LuqmanLength, SajdahLength,
  AhzabLength, SabaLength, FatirLength, YasinLength, SaffatLength, SadLength,
  ZumarLength, GafirLength, FussilatLength, SyuraLength, ZukhrufLength,
  DukhanLength, JasiyahLength, AhqafLength, MuhammadLength, FathLength,
  HujuratLength, QafLength, ZariyatLength, TurLength, NajmLength, QamarLength,
  RahmanLength, WaqiahLength, HadidLength, MujadalahLength, HasyrLength,
  MumtahanahLength, SaffLength, JumuahLength, MunafiqunLength, TagabunLength,
  TalaqLength, TahrimLength, MulkLength, QalamLength, HaqqahLength,
  MaarijLength, NuhLength, JinnLength, MuzzamilLength, MuddassirLength,
  QiyamahLength, InsanLength, MursalatLength, NabaLength, NaziatLength,
  AbasaLength, TakwirLength, InfitarLength, MutaffifinLength, InsyiqaqLength,
  BurujLength, TariqLength, AklaLength, GasyiyahLength, FajrLength, BaladLength,
  SyamsLength, LailLength, DuhaLength, SyarhLength, TinLength, AlaqLength,
  QadrLength, BayyinahLength, ZalzalahLength, AdiyatLength, QariahLength,
  TakasurLength, AsrLength, HumazahLength, FilLength, QuraisyLength, MaunLength,
  KausarLength, KafirunLength, NasrLength, LahabLength, IkhlasLength,
  FalaqLength, NasLength,

  FatihahAyahTransliterate, BaqarahAyahTransliterate, ImranAyahTransliterate,
  NisaAyahTransliterate, MaidahAyahTransliterate, AnamAyahTransliterate,
  ArafAyahTransliterate, AnfalAyahTransliterate, TaubahAyahTransliterate,
  YunusAyahTransliterate, HudAyahTransliterate, YusufAyahTransliterate,
  RadAyahTransliterate, IbrahimAyahTransliterate, HijrAyahTransliterate,
  NahlAyahTransliterate, IsraAyahTransliterate, KahfAyahTransliterate,
  MaryamAyahTransliterate, TahaAyahTransliterate, AnbiyaAyahTransliterate,
  HajjAyahTransliterate, MukminunAyahTransliterate, NurAyahTransliterate,
  FurqanAyahTransliterate, SyuaraAyahTransliterate, NamlAyahTransliterate,
  QasasAyahTransliterate, AnkabutAyahTransliterate, RumAyahTransliterate,
  LuqmanAyahTransliterate, SajdahAyahTransliterate, AhzabAyahTransliterate,
  SabaAyahTransliterate, FatirAyahTransliterate, YasinAyahTransliterate,
  SaffatAyahTransliterate, SadAyahTransliterate, ZumarAyahTransliterate,
  GafirAyahTransliterate, FussilatAyahTransliterate, SyuraAyahTransliterate,
  ZukhrufAyahTransliterate, DukhanAyahTransliterate, JasiyahAyahTransliterate,
  AhqafAyahTransliterate, MuhammadAyahTransliterate, FathAyahTransliterate,
  HujuratAyahTransliterate, QafAyahTransliterate, ZariyatAyahTransliterate,
  TurAyahTransliterate, NajmAyahTransliterate, QamarAyahTransliterate,
  RahmanAyahTransliterate, WaqiahAyahTransliterate, HadidAyahTransliterate,
  MujadalahAyahTransliterate, HasyrAyahTransliterate,
  MumtahanahAyahTransliterate, SaffAyahTransliterate, JumuahAyahTransliterate,
  MunafiqunAyahTransliterate, TagabunAyahTransliterate, TalaqAyahTransliterate,
  TahrimAyahTransliterate, MulkAyahTransliterate, QalamAyahTransliterate,
  HaqqahAyahTransliterate, MaarijAyahTransliterate, NuhAyahTransliterate,
  JinnAyahTransliterate, MuzzamilAyahTransliterate, MuddassirAyahTransliterate,
  QiyamahAyahTransliterate, InsanAyahTransliterate, MursalatAyahTransliterate,
  NabaAyahTransliterate, NaziatAyahTransliterate, AbasaAyahTransliterate,
  TakwirAyahTransliterate, InfitarAyahTransliterate,
  MutaffifinAyahTransliterate, InsyiqaqAyahTransliterate,
  BurujAyahTransliterate, TariqAyahTransliterate, AklaAyahTransliterate,
  GasyiyahAyahTransliterate, FajrAyahTransliterate, BaladAyahTransliterate,
  SyamsAyahTransliterate, LailAyahTransliterate, DuhaAyahTransliterate,
  SyarhAyahTransliterate, TinAyahTransliterate, AlaqAyahTransliterate,
  QadrAyahTransliterate, BayyinahAyahTransliterate, ZalzalahAyahTransliterate,
  AdiyatAyahTransliterate, QariahAyahTransliterate, TakasurAyahTransliterate,
  AsrAyahTransliterate, HumazahAyahTransliterate, FilAyahTransliterate,
  QuraisyAyahTransliterate, MaunAyahTransliterate, KausarAyahTransliterate,
  KafirunAyahTransliterate, NasrAyahTransliterate, LahabAyahTransliterate,
  IkhlasAyahTransliterate, FalaqAyahTransliterate, NasAyahTransliterate,

  FatihahAyahTranslate, BaqarahAyahTranslate, ImranAyahTranslate,
  NisaAyahTranslate, MaidahAyahTranslate, AnamAyahTranslate, ArafAyahTranslate,
  AnfalAyahTranslate, TaubahAyahTranslate, YunusAyahTranslate, HudAyahTranslate,
  YusufAyahTranslate, RadAyahTranslate, IbrahimAyahTranslate, HijrAyahTranslate,
  NahlAyahTranslate, IsraAyahTranslate, KahfAyahTranslate, MaryamAyahTranslate,
  TahaAyahTranslate, AnbiyaAyahTranslate, HajjAyahTranslate,
  MukminunAyahTranslate, NurAyahTranslate, FurqanAyahTranslate,
  SyuaraAyahTranslate, NamlAyahTranslate, QasasAyahTranslate,
  AnkabutAyahTranslate, RumAyahTranslate, LuqmanAyahTranslate,
  SajdahAyahTranslate, AhzabAyahTranslate, SabaAyahTranslate,
  FatirAyahTranslate, YasinAyahTranslate, SaffatAyahTranslate, SadAyahTranslate,
  ZumarAyahTranslate, GafirAyahTranslate, FussilatAyahTranslate,
  SyuraAyahTranslate, ZukhrufAyahTranslate, DukhanAyahTranslate,
  JasiyahAyahTranslate, AhqafAyahTranslate, MuhammadAyahTranslate,
  FathAyahTranslate, HujuratAyahTranslate, QafAyahTranslate,
  ZariyatAyahTranslate, TurAyahTranslate, NajmAyahTranslate, QamarAyahTranslate,
  RahmanAyahTranslate, WaqiahAyahTranslate, HadidAyahTranslate,
  MujadalahAyahTranslate, HasyrAyahTranslate, MumtahanahAyahTranslate,
  SaffAyahTranslate, JumuahAyahTranslate, MunafiqunAyahTranslate,
  TagabunAyahTranslate, TalaqAyahTranslate, TahrimAyahTranslate,
  MulkAyahTranslate, QalamAyahTranslate, HaqqahAyahTranslate,
  MaarijAyahTranslate, NuhAyahTranslate, JinnAyahTranslate,
  MuzzamilAyahTranslate, MuddassirAyahTranslate, QiyamahAyahTranslate,
  InsanAyahTranslate, MursalatAyahTranslate, NabaAyahTranslate,
  NaziatAyahTranslate, AbasaAyahTranslate, TakwirAyahTranslate,
  InfitarAyahTranslate, MutaffifinAyahTranslate, InsyiqaqAyahTranslate,
  BurujAyahTranslate, TariqAyahTranslate, AklaAyahTranslate,
  GasyiyahAyahTranslate, FajrAyahTranslate, BaladAyahTranslate,
  SyamsAyahTranslate, LailAyahTranslate, DuhaAyahTranslate, SyarhAyahTranslate,
  TinAyahTranslate, AlaqAyahTranslate, QadrAyahTranslate, BayyinahAyahTranslate,
  ZalzalahAyahTranslate, AdiyatAyahTranslate, QariahAyahTranslate,
  TakasurAyahTranslate, AsrAyahTranslate, HumazahAyahTranslate,
  FilAyahTranslate, QuraisyAyahTranslate, MaunAyahTranslate,
  KausarAyahTranslate, KafirunAyahTranslate, NasrAyahTranslate,
  LahabAyahTranslate, IkhlasAyahTranslate, FalaqAyahTranslate, NasAyahTranslate,

  FatihahAyahAnnotation, BaqarahAyahAnnotation, ImranAyahAnnotation,
  NisaAyahAnnotation, MaidahAyahAnnotation, AnamAyahAnnotation,
  ArafAyahAnnotation, AnfalAyahAnnotation, TaubahAyahAnnotation,
  YunusAyahAnnotation, HudAyahAnnotation, YusufAyahAnnotation,
  RadAyahAnnotation, IbrahimAyahAnnotation, HijrAyahAnnotation,
  NahlAyahAnnotation, IsraAyahAnnotation, KahfAyahAnnotation,
  MaryamAyahAnnotation, TahaAyahAnnotation, AnbiyaAyahAnnotation,
  HajjAyahAnnotation, MukminunAyahAnnotation, NurAyahAnnotation,
  FurqanAyahAnnotation, SyuaraAyahAnnotation, NamlAyahAnnotation,
  QasasAyahAnnotation, AnkabutAyahAnnotation, RumAyahAnnotation,
  LuqmanAyahAnnotation, SajdahAyahAnnotation, AhzabAyahAnnotation,
  SabaAyahAnnotation, FatirAyahAnnotation, YasinAyahAnnotation,
  SaffatAyahAnnotation, SadAyahAnnotation, ZumarAyahAnnotation,
  GafirAyahAnnotation, FussilatAyahAnnotation, SyuraAyahAnnotation,
  ZukhrufAyahAnnotation, DukhanAyahAnnotation, JasiyahAyahAnnotation,
  AhqafAyahAnnotation, MuhammadAyahAnnotation, FathAyahAnnotation,
  HujuratAyahAnnotation, QafAyahAnnotation, ZariyatAyahAnnotation,
  TurAyahAnnotation, NajmAyahAnnotation, QamarAyahAnnotation,
  RahmanAyahAnnotation, WaqiahAyahAnnotation, HadidAyahAnnotation,
  MujadalahAyahAnnotation, HasyrAyahAnnotation, MumtahanahAyahAnnotation,
  SaffAyahAnnotation, JumuahAyahAnnotation, MunafiqunAyahAnnotation,
  TagabunAyahAnnotation, TalaqAyahAnnotation, TahrimAyahAnnotation,
  MulkAyahAnnotation, QalamAyahAnnotation, HaqqahAyahAnnotation,
  MaarijAyahAnnotation, NuhAyahAnnotation, JinnAyahAnnotation,
  MuzzamilAyahAnnotation, MuddassirAyahAnnotation, QiyamahAyahAnnotation,
  InsanAyahAnnotation, MursalatAyahAnnotation, NabaAyahAnnotation,
  NaziatAyahAnnotation, AbasaAyahAnnotation, TakwirAyahAnnotation,
  InfitarAyahAnnotation, MutaffifinAyahAnnotation, InsyiqaqAyahAnnotation,
  BurujAyahAnnotation, TariqAyahAnnotation, AklaAyahAnnotation,
  GasyiyahAyahAnnotation, FajrAyahAnnotation, BaladAyahAnnotation,
  SyamsAyahAnnotation, LailAyahAnnotation, DuhaAyahAnnotation,
  SyarhAyahAnnotation, TinAyahAnnotation, AlaqAyahAnnotation,
  QadrAyahAnnotation, BayyinahAyahAnnotation, ZalzalahAyahAnnotation,
  AdiyatAyahAnnotation, QariahAyahAnnotation, TakasurAyahAnnotation,
  AsrAyahAnnotation, HumazahAyahAnnotation, FilAyahAnnotation,
  QuraisyAyahAnnotation, MaunAyahAnnotation, KausarAyahAnnotation,
  KafirunAyahAnnotation, NasrAyahAnnotation, LahabAyahAnnotation,
  IkhlasAyahAnnotation, FalaqAyahAnnotation, NasAyahAnnotation
{
  const Quran._();

  static Quran get instance => _instance;
  static const Quran _instance = Quran._();
}

mixin Surah on QuranBinder {}

mixin Ayah on QuranBinder {}
